# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          minung--dev-log
paginate:       5
baseurl:        "/"
url:            "https://blog.minung.dev"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Custom vars
version:        1.0.0
github:
  repo:         https://github.com/hmu332233/blog

# Gems
plugins:
  - jekyll-paginate

# deployment
host: 0.0.0.0
port: 3000